apiVersion: v1
kind: Pod
metadata:
  name: util
  namespace: demo
spec:
  containers:
  - env:
    - name: MONGODB_NAME
      value: source
    - name: MONGODB_NAMESPACE
      value: demo
    image: arnobkumarsaha/mongo-util
    imagePullPolicy: Always
    name: util
    resources: {}
  dnsPolicy: ClusterFirst
  serviceAccountName: mongo-util
  restartPolicy: Always

