apiVersion: v1
kind: Pod
metadata:
  name: util
  namespace: demo
spec:
  containers:
  - env:
    - name: MONGODB_NAME
      value: "repl6"
    - name: MONGODB_NAMESPACE
      value: "demo"
    - name: INSERTION_SIZE_IN_GiB
      value: "1" # Default 5
    - name: BATCH_SIZE
      value: "10000" # Default 100000
    - name: NUMBER_OF_GOROUTINE
      value: "3" # Default 5
    image: arnobkumarsaha/mongo-util
    imagePullPolicy: Always
    name: util
    resources:
      requests:
        cpu: 1
        memory: 1Gi
  dnsPolicy: ClusterFirst
  serviceAccountName: mongo-util
  restartPolicy: Always

