apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: count
  name: count
  namespace: demo
spec:
  containers:
  - env:
    - name: MONGODB_NAME
      value: mg-rs
    - name: MONGODB_NAMESPACE
      value: demo
    image: arnobkumarsaha/object_count
    imagePullPolicy: Always
    name: count
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

