apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-util
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongo-util
  namespace: demo
rules:
  - apiGroups: ["kubedb.com"]
    resources: ["mongodbs"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-util
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: mongo-util
    apiGroup: ""
roleRef:
  kind: Role
  name: mongo-util
  apiGroup: rbac.authorization.k8s.io